version: "3"
services:
    postgres:
        image: postgres:13.3
        container_name: postgres
        environment:
            POSTGRES_DB: rdtsdb
            POSTGRES_USER: rdts
            POSTGRES_PASSWORD: rdts
        volumes:
            - sql_volume:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - rdts_network

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:2022-11-15-1
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "5050:80"
        networks:
            - rdts_network

    server:
        image: pechenuxa1/rdts_server:1.1
        #build:
        #    context: .
        container_name: backend
        depends_on:
            - postgres
        volumes:
            - testsuites_volume:/testsuites
            - results_volume:/results
        ports:
            - "8000:8000"
        networks:
            - rdts_network

volumes:
    sql_volume:
    testsuites_volume:
    results_volume:
networks:
    rdts_network:
